language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
branches:
  only:
    - /^7.x/
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
  - FEDORA_VERSION="3.8.1"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_collection.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solr_search.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solr_metadata.git
  - git clone -b 7.x git://github.com/Islandora/islandora_bookmark.git

  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_solution_pack_entities
  - ln -s $HOME/islandora_solr_search sites/all/modules/islandora_solr_search
  - ln -s $HOME/islandora_solr_metadata sites/all/modules/islandora_solr_metadata
  - ln -s $HOME/islandora_solution_pack_collection sites/all/modules/islandora_solution_pack_collection
  - ln -s $HOME/islandora_bookmark sites/all/modules/islandora_bookmark
  - drush -u 1 en --yes islandora_entities islandora_bookmark
script:
  - ant -buildfile sites/all/modules/islandora_solution_pack_entities/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_solution_pack_entities
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_entities
  - phpcpd --names *.module,*.inc,*.test,*.install sites/all/modules/islandora_solution_pack_entities
  - drush test-run --uri=http://localhost:8081 "Islandora Islandora Entities"
notifications:
  irc: "irc.freenode.org#islandora"
